-- ============================================================================
--  Architecture Intelligence Platform — PostgreSQL bootstrap
-- ----------------------------------------------------------------------------
--  Database: architecture_ai (created by the postgres container from POSTGRES_DB)
--  Mounted into /docker-entrypoint-initdb.d/ and run ONCE on a fresh volume.
--  Idempotent, so it can also be applied by hand:
--      psql "$DATABASE_URL" -f db/init.sql
-- ============================================================================
--
--  WHAT THIS FILE DOES — AND DELIBERATELY DOES NOT DO
--
--  It installs the pgvector extension. That is all.
--
--  This file used to create six tables — documents, chunks, embeddings,
--  architecture_decisions, technical_debts, project_memory — and NOT ONE of
--  them was ever read or written by any code. Worse than dead weight: their
--  presence implied that ADRs, technical debt and project memory live in the
--  database. They do not. They live in Markdown, under architecture/adr/,
--  quality/technical-debt/ and project-memory/, because they are reviewed in
--  pull requests by humans, and a row in a table cannot be reviewed.
--
--  The one table that IS used — the RAG chunk store — is owned and created by
--  the application (VectorStore, rag-mcp), lazily on first use. That is
--  deliberate: its embedding column is vector(N) where N comes from the
--  configured embedding provider, so the schema cannot be written down ahead of
--  configuration. See rag-mcp/src/main/resources/application.yml:
--  "the RAG store creates its own schema lazily, per request".
--
--  If you add a table here, add the code that uses it in the same commit.
--  Schema that nothing reads is drift, and drift is what this platform exists
--  to detect.
-- ============================================================================

-- pgvector: required by rag-mcp when the optional knowledge layer is enabled
-- (KNOWLEDGE_ENABLED=true). Harmless when it is not.
--
-- The application attempts this too, but not every deployment grants the app
-- role permission to create extensions — on managed Postgres it is usually
-- pre-installed. Doing it here, as the bootstrap superuser, is the reliable path.
CREATE EXTENSION IF NOT EXISTS vector;
