#!/usr/bin/env bash
# ============================================================================
#  daily-scan.sh — AIP Daily Workflow
# ----------------------------------------------------------------------------
#  1. Read the merged digital-twin state (fallback: per-source /api/*/state).
#  2. Generate the DAILY markdown report from digital-twin-core.
#  3. Write it to reports/daily/<DATE>.md and append a line to INDEX.md.
#
#  Degrades gracefully: an unreachable server is recorded as DATA_STALE in the
#  report rather than aborting the run. Suggested cron: 07:00 daily.
# ============================================================================
set -euo pipefail

# shellcheck disable=SC1091
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
aip_load_env

DATE="$(date +%F)"
DAILY_DIR="${REPORTS_DIR}/daily"
OUT="${DAILY_DIR}/${DATE}.md"
INDEX="${DAILY_DIR}/INDEX.md"
mkdir -p "${DAILY_DIR}"

TWIN_URL="$(aip_twin_url)"
STALE=0   # set to 1 if any source could not be reached

# --- 1. Twin state (with per-source fallback) -------------------------------
log "fetching twin state from ${TWIN_URL}/api/twin/state"
STATE_JSON=""
if STATE_JSON="$(aip_get "${TWIN_URL}/api/twin/state")"; then
  log "twin state OK"
else
  warn "twin state unreachable — falling back to per-source /api/*/state"
  STALE=1
  for svc in jira github sonar; do
    case "${svc}" in
      jira)   url="$(aip_jira_url)" ;;
      github) url="$(aip_github_url)" ;;
      sonar)  url="$(aip_sonar_url)" ;;
    esac
    if aip_get "${url}/api/${svc}/state" >/dev/null; then
      log "  ${svc}-mcp state OK"
    else
      warn "  ${svc}-mcp state UNREACHABLE (DATA_STALE)"
    fi
  done
fi

# --- 2. DAILY report --------------------------------------------------------
log "generating DAILY report from ${TWIN_URL}/api/twin/report?type=DAILY"
REPORT_MD=""
if REPORT_JSON="$(aip_get "${TWIN_URL}/api/twin/report?type=DAILY")"; then
  # The markdown lives in the McpResponse `data` field; fall back to raw body.
  if md="$(aip_json_field "${REPORT_JSON}" '.data // empty')" && [[ -n "${md}" ]]; then
    REPORT_MD="${md}"
  else
    REPORT_MD="${REPORT_JSON}"
  fi
else
  warn "DAILY report unreachable — writing a DATA_STALE placeholder"
  STALE=1
  REPORT_MD="_(digital-twin-core unreachable — no report body)_"
fi

# --- 3. Write report + index ------------------------------------------------
{
  echo "# Daily Report — ${DATE}"
  echo
  if [[ "${STALE}" -eq 1 ]]; then
    echo "> **STATUS: DATA_STALE** — one or more sources could not be reached at"
    echo "> scan time; figures below may be incomplete. See automation logs."
    echo
  fi
  echo "_Generated by automation/daily-scan.sh at $(date +'%F %T')._"
  echo
  echo "---"
  echo
  printf '%s\n' "${REPORT_MD}"
} > "${OUT}"
log "wrote ${OUT}"

# Append a one-line summary to the index (create header if new).
if [[ ! -f "${INDEX}" ]]; then
  printf '# Daily Reports — Index\n\n| Date | Status | Report |\n|------|--------|--------|\n' > "${INDEX}"
fi
status_label="OK"; [[ "${STALE}" -eq 1 ]] && status_label="DATA_STALE"
printf '| %s | %s | [%s](./%s.md) |\n' "${DATE}" "${status_label}" "${DATE}" "${DATE}" >> "${INDEX}"
log "appended ${DATE} to ${INDEX}"

log "daily-scan complete (status: ${status_label})"
